services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app
    environment:
      - TOKENIZERS_PARALLELISM=false
      - OPENAI_API_KEY=your_openai_api_key  # TODO: Replace with your OpenAI API key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 10s
      retries: 100
      start_period: 10s

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../ui:/ui
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/"]
      interval: 10s
      timeout: 10s
      retries: 100
      start_period: 10s
